INSERT INTO Addresses VALUES ('gata', '1', '12345', 'stad')
INSERT INTO Breeders VALUES ('Anna', 'Andersson', 'a@d.com')
INSERT INTO Owners VALUES ('Test', 'Testson', 'T@d.com')
INSERT INTO Breeds VALUES ('SWB')
INSERT INTO Horses VALUES ('Häst1', 'sto', '2020', '', '', 1, 1, 1, 1)